# -*- coding: utf-8 -*-
"""Productreview_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bmmKaEHZ5njcIS-_5GgWpo_oOeJwKmSb
"""

import streamlit as st

# Title of the app
st.title("Product Review App")

# Initialize session state to store reviews
if 'reviews' not in st.session_state:
    st.session_state.reviews = []

# Review input
review = st.text_area("Write your review here:")

# Rating input (1 to 5)
rating = st.selectbox("Rate the product:", [1, 2, 3, 4, 5])

# Submit button
if st.button("Submit Review"):
    if review:
        # Store the review and rating in session state
        st.session_state.reviews.append({"review": review, "rating": rating})
        st.success("Review submitted successfully!")
    else:
        st.error("Please write a review before submitting.")

# Display submitted reviews
st.subheader("Submitted Reviews:")
for index, rev in enumerate(st.session_state.reviews):
    st.write(f"**Review {index + 1}:** {rev['review']}")
    st.write(f"**Rating:** {rev['rating']} ⭐")
    st.write("---")